# Generated by Django 6.0.3 on 2026-03-25 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('DIAGNOSIS', 'Diagnosis'), ('PRESCRIPTION', 'Prescription'), ('LAB_TEST', 'Lab Test'), ('VACCINATION', 'Vaccination'), ('CONSULTATION', 'Consultation'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'PROVIDER'}, on_delete=django.db.models.deletion.PROTECT, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', '-created_at'], name='records_hea_patient_67dcba_idx'), models.Index(fields=['doctor', '-created_at'], name='records_hea_doctor__7a6197_idx'), models.Index(fields=['is_approved'], name='records_hea_is_appr_81c752_idx')],
            },
        ),
    ]
