# Generated by Django 6.0.3 on 2026-03-27 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_user_id_ea8c9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_action_e33994_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_content_4c2ead_idx',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_type',
            field=models.CharField(blank=True, choices=[('PATIENT', 'Patient'), ('PROVIDER', 'Provider'), ('ADMIN', 'Admin')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='nin_authorized',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_subject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='records.healthrecord'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('READ', 'Read'), ('WRITE_REQUEST', 'Write Request'), ('WRITE_APPROVED', 'Write Approved'), ('WRITE_REJECTED', 'Write Rejected'), ('CONSENT_GRANTED', 'Consent Granted'), ('CONSENT_REVOKED', 'Consent Revoked')], max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
    ]
